POST http://localhost:3000/submit
Content-Type: application/json

{
    "id": "1",
    "assignment": {
        "text": "this is sample assignment",
        "moduleCode": "1",
        "moduleTitle": "SOA"
    },
    "url": "http://localhost/200s"
}